server:
  servlet:
    context-path: /api
  port: 8082

spring:
  application:
    name: AuditService
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ylab-service
            client-secret: dmSxwDwyA0amZPNUcg2uwR4KE9EwOhxi
            scope:
              - openid
              - profile
              - email
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/api/auth/user
        provider:
          keycloak:
            authorization-uri: http://localhost:8069/realms/ylab-test/protocol/openid-connect/auth
            token-uri: http://localhost:8069/realms/ylab-test/protocol/openid-connect/token
            user-info-uri: http://localhost:8069/realms/ylab-test/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8069/realms/ylab-test/protocol/openid-connect/certs
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/db.changelog-master.xml

  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema:
        registry:
          url: http://localhost:8071
      specific:
        avro:
          reader: true
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      group-id: audit-service
      auto-offset-reset: earliest

app:
  topic: audit-topic-v1